
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: arlo
rules:
- apiGroups:
  - arlon.org
  resources:
  - clusterregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arlon.org
  resources:
  - clusterregistrations/finalizers
  verbs:
  - update
- apiGroups:
  - arlon.org
  resources:
  - clusterregistrations/status
  verbs:
  - get
  - patch
  - update
#- apiGroups: [""]
#  resources: ["secrets"]
#  verbs: ["get", "watch", "list"]
